# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    allow:
      - dependency-type: "direct"
    versioning-strategy: increase-if-necessary
    groups:
      dependencies:
        patterns:
          - "*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
  - package-ecosystem: "gradle"
    directory: "/src/examples/gradle/buildSrc"
    schedule:
      interval: "monthly"
    groups:
      dependencies:
        patterns:
          - "*"
