title: Plamen Totev's Blog
url: "https://plamentotev.github.io"
author: Plamen Totev

twitter:
  username: TotevPlamen
  card: summary

social:
  name: Plamen Totev
  links:
    - https://github.com/plamentotev
    - https://twitter.com/TotevPlamen
    - https://www.linkedin.com/in/ptotev/

theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-default-layout
  - jekyll-titles-from-headings
  - jekyll-optional-front-matter
  - jekyll-asciidoc

titles_from_headings:
  strip_title: true
  collections: true

show_excerpts: true
excerpt_separator: <!--more-->

exclude:
  - README.md
  - examples

asciidoc:
  excerpt_separator: "\n//more\n"
asciidoctor:
  attributes:
    source-highlighter: rouge
