name: Build and deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            vendor/bundle
            ~/.m2/repository
          key: cache-${{ hashFiles('**/Gemfile', '**/pom.xml') }}
          restore-keys: |
            cache-
      - run: export JAVA_HOME="$JAVA_HOME_17_X64" && cd articles/java && mvn --batch-mode verify
      - uses: helaili/jekyll-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target_branch: 'gh-pages'
